import { StyleSheet } from 'react-native';
import { AppTheme } from '@theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 10,
    },
    bookingId: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textSecondary,
      marginBottom: 8,
      textDecorationLine: 'underline',
    },
    mechanicCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    mechanicImage: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: theme.colors.gray100,
    },
    mechanicInfo: {
      flex: 1,
      marginLeft: 12,
    },
    mechanicName: {
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
    },
    mechanicStats: {
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
      marginTop: 4,
    },
    emptyContainer: {
      backgroundColor: theme.colors.white,
      borderRadius: 12,
      padding: 32,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    emptyTitle: {
      fontSize: 16,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
      marginTop: 12,
    },
    emptySub: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      marginTop: 8,
      lineHeight: 20,
    },
    partsSectionTitle: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.red,
      marginBottom: 12,
    },
    partCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 12,
      padding: 12,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    partHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    partVendor: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
    },
    partLocation: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
    },
    partRating: {
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.GoldenYellow,
    },
    partBody: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    partDetails: {
      flex: 1,
      paddingRight: 8,
    },
    partTitle: {
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.textPrimary,
      marginBottom: 8,
    },
    partBullet: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    partBulletText: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
      marginLeft: 4,
    },
    partPriceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    partPrice: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
    },
    partMrp: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textMuted,
      textDecorationLine: 'line-through',
      marginLeft: 8,
    },
    partImage: {
      width: 80,
      height: 70,
      borderRadius: 8,
      backgroundColor: theme.colors.gray50,
    },
    quantityContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.DeepGreen,
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      position: 'absolute',
      bottom: 0,
      right: 0,
    },
    quantityBtn: {
      fontSize: 14,
      color: theme.colors.white,
      paddingHorizontal: 4,
    },
    quantityText: {
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.white,
      marginHorizontal: 8,
    },
    billSummaryCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    billTitle: {
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
      marginLeft: 8,
    },
    billHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    billRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    billLabel: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
    },
    billValue: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
    },
    taxNote: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textMuted,
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.gray100,
      marginVertical: 12,
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    totalLabel: {
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
    },
    totalValue: {
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
    },
    footer: {
      padding: 20,
      paddingBottom: 30,
      backgroundColor: theme.colors.white,
      borderTopWidth: 1,
      borderTopColor: theme.colors.gray100,
    },
    basicServiceCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    basicServiceTitle: {
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.textPrimary,
      marginBottom: 8,
    },
    basicServiceCostRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    basicServiceCostLabel: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
    },
    basicServiceCostValue: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
    },
    basicServiceCostDiscount: {
      color: theme.colors.success,
    },
    staticQuantityText: {
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textPrimary,
      marginTop: 4,
      textAlign: 'center',
    },
    partTractorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    partTractorText: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
      marginLeft: 4,
    },
    redNoteBox: {
      backgroundColor: '#FFF0F0',
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
    },
    redNoteText: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.red,
      lineHeight: 16,
    },
    dottedDivider: {
      height: 1,
      borderStyle: 'dashed',
      borderWidth: 1,
      borderColor: theme.colors.gray200,
      marginVertical: 12,
      borderRadius: 1,
    },
  });
