import { StyleSheet } from 'react-native';
import { SW, SH, SF } from '@utils/Dimensions';
import { AppTheme } from '@theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      paddingHorizontal: SW(16),
      paddingTop: SH(15),
      paddingBottom: SH(100),
    },
    bookingId: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoMedium,
      color: theme.colors.textSecondary,
      marginBottom: SH(10),
      textDecorationLine: 'underline',
    },
    mechanicCard: {
      backgroundColor: theme.colors.white,
      borderRadius: SW(12),
      padding: SW(12),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: SH(16),
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    mechanicImage: {
      width: SW(50),
      height: SW(50),
      borderRadius: SW(25),
      backgroundColor: theme.colors.gray100,
    },
    mechanicInfo: {
      flex: 1,
      marginLeft: SW(12),
    },
    mechanicName: {
      fontSize: SF(15),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    mechanicStats: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
      marginTop: SH(2),
    },
    emptyContainer: {
      backgroundColor: theme.colors.white,
      borderRadius: SW(12),
      padding: SW(30),
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: SH(16),
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    emptyTitle: {
      fontSize: SF(16),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
      marginTop: SH(15),
    },
    emptySub: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      marginTop: SH(8),
      lineHeight: SH(20),
    },
    partsSectionTitle: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.red,
      marginBottom: SH(12),
    },
    partCard: {
      backgroundColor: theme.colors.white,
      borderRadius: SW(12),
      padding: SW(12),
      marginBottom: SH(16),
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    partHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: SH(10),
    },
    partVendor: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    partLocation: {
      fontSize: SF(11),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
    },
    partRating: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.GoldenYellow,
    },
    partBody: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    partDetails: {
      flex: 1,
      paddingRight: SW(10),
    },
    partTitle: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
      marginBottom: SH(8),
    },
    partBullet: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: SH(4),
    },
    partBulletText: {
      fontSize: SF(11),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
      marginLeft: SW(6),
    },
    partPriceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: SH(8),
    },
    partPrice: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    partMrp: {
      fontSize: SF(11),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textMuted,
      textDecorationLine: 'line-through',
      marginLeft: SW(8),
    },
    partImage: {
      width: SW(80),
      height: SH(70),
      borderRadius: SW(8),
      backgroundColor: theme.colors.gray50,
    },
    quantityContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.DeepGreen,
      borderRadius: SW(6),
      paddingHorizontal: SW(8),
      paddingVertical: SH(4),
      position: 'absolute',
      bottom: SH(0),
      right: SW(0),
    },
    quantityBtn: {
      fontSize: SF(14),
      color: theme.colors.white,
      paddingHorizontal: SW(6),
    },
    quantityText: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.white,
      marginHorizontal: SW(8),
    },
    billSummaryCard: {
      backgroundColor: theme.colors.white,
      borderRadius: SW(12),
      padding: SW(16),
      marginBottom: SH(20),
      borderWidth: 1,
      borderColor: theme.colors.gray100,
    },
    billTitle: {
      fontSize: SF(15),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
      marginLeft: SW(10),
    },
    billHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: SH(15),
    },
    billRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: SH(10),
    },
    billLabel: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
    },
    billValue: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoMedium,
      color: theme.colors.textPrimary,
    },
    taxNote: {
      fontSize: SF(11),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textMuted,
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.gray100,
      marginVertical: SH(12),
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    totalLabel: {
      fontSize: SF(15),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    totalValue: {
      fontSize: SF(15),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    footer: {
      padding: SW(20),
      paddingBottom: SH(30),
      backgroundColor: theme.colors.white,
      borderTopWidth: 1,
      borderTopColor: theme.colors.gray100,
    },
  });
