import { StyleSheet, Dimensions } from 'react-native';
import { AppTheme } from '@theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    header: {
      backgroundColor: theme.colors.DeepGreen,
      paddingTop: 12,
      paddingBottom: 16,
      paddingHorizontal: 16,
      marginBottom: 10
    },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 12,
    },
    searchBox: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.white,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingLeft: 5,
      gap: 10,
      height: 34,
    },
    searchInput: {
      flex: 1,
      fontSize: 13,
      color: theme.colors.textPrimary,
      fontFamily: theme.fontfamily.poppinsRegular,
      padding: 0
    },
    headerActions: {
      flexDirection: 'row',
      gap: 10,
    },
    iconCircle: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: theme.colors.white + '26',
      alignItems: 'center',
      justifyContent: 'center',
    },
    notifDot: {
      position: 'absolute',
      top: 8,
      right: 8,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primaryRed,
      borderWidth: 1.5,
      borderColor: theme.colors.white,
    },
    addressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    addressText: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 12,
    },
    addressBold: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
    },
    scrollContent: {
      paddingBottom: 10,
    },
    sliderSection: {
      marginVertical: 5,
      marginTop: 0
    },
    heroCardContainer: {
      height: 190,
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: 'transparent',
    },
    heroCard: {
      height: '100%',
      width: '100%',
      borderRadius: 20,
      overflow: 'hidden',
      position: 'relative',
      backgroundColor: 'transparent',
    },
    heroGradient: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: '100%',
      justifyContent: 'flex-end',
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    heroOverlay: {
      backgroundColor: theme.colors.black + '4D',
      position: 'absolute',
      top: 0, left: 0, right: 0, bottom: 0,
    },
    heroTitle: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 15,
      marginBottom: 12,
      lineHeight: 24,
    },
    heroCta: {
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.white,
      borderRadius: 25,
      paddingHorizontal: 24,
      paddingVertical: 5,
    },
    heroCtaText: {
      color: theme.colors.black,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      fontSize: 14,
    },
    middleCardContainer: {
      height: 200,
      borderRadius: 20,
      overflow: 'hidden',
    },
    networkCardContainer: {
      height: 180,
      borderRadius: 20,
      overflow: 'hidden',
    },
    dots: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 8,
      marginVertical: 12,
    },
    heroDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.gray200,
    },
    heroDotActive: {
      backgroundColor: theme.colors.DeepGreen,
      width: 24,
    },
    middleDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.gray200,
    },
    middleDotActive: {
      backgroundColor: theme.colors.brightRed,
      width: 24,
    },
    networkDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.gray200,
    },
    networkDotActive: {
      backgroundColor: theme.colors.red,
      width: 24,
    },
    section: {
      paddingHorizontal: 16,
      marginBottom: 24,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
    },
    sectionTitle: {
      fontFamily: theme.fontfamily.poppinsSemiBold,
      fontSize: 14,
      color: theme.colors.black,
      marginBottom: 10
    },
    seeMore: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 14,
      color: theme.colors.DeepGreen,
      textDecorationLine: 'underline',
    },
    serviceGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    serviceCard: {
      width: "48%",
      borderRadius: 20,
      padding: 16,
      minHeight: 80,
      overflow: 'hidden',
      position: 'relative',
      elevation: 3,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
    },
    serviceCardDecorator: {
      position: 'absolute',
      top: -9,
      left: -18,
      width: 94,
      height: 94,
      borderRadius: 47,
    },
    serviceTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
      zIndex: 1,
    },
    serviceIconWrap: {
      paddingHorizontal: 6,
      paddingVertical: 6,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    serviceLabel: {
      flex: 1,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 12,
    },
    serviceSub: {
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 11,
      color: theme.colors.textSecondary,
    },
    partCard: {
      width: 170,
      backgroundColor: theme.colors.white,
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: theme.colors.faintGray,
    },
    partImageWrap: {
      alignItems: 'center',
      marginBottom: 10,
    },
    partName: {
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 12,
      color: theme.colors.gray800,
      marginBottom: 8,
      lineHeight: 18,
    },
    partPriceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 6,
    },
    partPrice: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 15,
      color: theme.colors.black,
    },
    partMrp: {
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 14,
      color: theme.colors.gray400,
      textDecorationLine: 'line-through',
    },
    partDiscount: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 12,
      color: theme.colors.greenSuccess,
    },
    categoryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      marginTop: 10,
    },
    categoryItem: {
      width: (SCREEN_WIDTH - 32 - 24) / 3, // (Total width - Section padding - gaps) / 3
      alignItems: 'center',
      marginBottom: 20,
    },
    categoryImageWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
      overflow: 'hidden',
    },
    categoryLabel: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 10,
      color: theme.colors.gray700,
      textAlign: 'center',
      lineHeight: 15,
    },
    adBannerWrap: {
      marginHorizontal: 16,
      marginBottom: 24,
      borderRadius: 16,
      overflow: 'hidden',
    },
    proBannerCard: {
      borderRadius: 16,
      overflow: 'hidden',
      minHeight: 154,
    },
    proBannerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      paddingLeft: 16,
    },
    proBannerLeft: {
      flex: 1,
      paddingRight: 8,
      marginRight: 15
    },
    proBannerBadge: {
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.white + '38',
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginBottom: 8,
    },
    proBannerBadgeText: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 11,
      letterSpacing: 1,
    },
    proBannerTitle: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 12,
      lineHeight: 22,
      marginBottom: 8,
    },
    proBannerTitleDark: {
      color: theme.colors.navyBlue,
    },
    proBannerBullets: {
      marginBottom: 12,
      gap: 4,
    },
    proBannerBullet: {
      color: theme.colors.white + 'E6',
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 12,
      lineHeight: 15,
    },
    proBannerBulletDark: {
      color: theme.colors.gray600,
    },
    proBannerBtn: {
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.white,
      borderRadius: 6,
      paddingHorizontal: 14,
      paddingVertical: 6,
    },
    proBannerBtnText: {
      color: theme.colors.darkRed,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 12,
    },
    proBannerImageWrap: {
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingRight: 4,
    },
    middleBannerCard: {
      width: '100%',
      height: '100%',
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: 'transparent',
    },
    middleBannerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      paddingLeft: 16,
    },
    middleBannerLeft: {
      flex: 1,
      paddingRight: 8,
      marginRight: 15,
    },
    middleBannerBadge: {
      alignSelf: 'flex-start',
      borderRadius: 6,
      paddingVertical: 5,
    },
    middleBannerBadgeText: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsBold,
      fontSize: 13,
      letterSpacing: 1,
    },
    middleBannerTitle: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 12,
    },
    middleBannerTitleDark: {
      color: theme.colors.navyBlue,
    },
    middleBannerBullets: {
      marginBottom: 12,
      gap: 4,
    },
    middleBannerBullet: {
      color: theme.colors.white + 'E6',
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 12,
      lineHeight: 15,
    },
    middleBannerBulletDark: {
      color: theme.colors.gray600,
    },
    middleBannerBtn: {
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.white,
      borderRadius: 6,
      paddingHorizontal: 14,
      paddingVertical: 6,
    },
    middleBannerBtnText: {
      color: theme.colors.darkRed,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 12,
    },
    middleBannerImageWrap: {
      width: 120,
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    networkBannerCard: {
      width: '100%',
      height: '100%',
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: 'transparent',
    },
    networkBannerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      paddingLeft: 16,
    },
    networkBannerLeft: {
      flex: 1,
      paddingRight: 8,
      marginRight: 15,
    },
    networkBannerBadge: {
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.white + '38',
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginBottom: 8,
    },
    networkBannerBadgeText: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 11,
      letterSpacing: 1,
    },
    networkBannerTitle: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      fontSize: 14,
      lineHeight: 22,
      marginBottom: 8,
    },
    networkBannerTitleDark: {
      color: theme.colors.navyBlue,
    },
    networkBannerBullets: {
      marginBottom: 12,
      gap: 4,
    },
    networkBannerBullet: {
      color: theme.colors.white + 'E6',
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 12,
      lineHeight: 15,
    },
    networkBannerBulletDark: {
      color: theme.colors.gray600,
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsRegular,
    },

    networkBannerImageWrap: {
      width: 120,
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    videoThumb: {
      width: 200,
      height: 120,
      borderRadius: 16,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    playButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.colors.white + 'E6',
      alignItems: 'center',
      justifyContent: 'center',
    },
    playIcon: {
      fontSize: 18,
      color: theme.colors.black,
      marginLeft: 4,
    },
    stepsCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 20,
      padding: 24,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
    },
    stepsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 24,
    },
    stepsBorderLeft: {
      width: 3,
      height: 28,
      backgroundColor: theme.colors.primaryRed,
      borderRadius: 2,
    },
    stepsTitle: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 16,
      color: theme.colors.black,
    },
    stepRow: {
      flexDirection: 'row',
      gap: 16,
      marginBottom: 20,
      alignItems: 'flex-start',
    },
    stepBadge: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: theme.colors.darkSlaty,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    stepNum: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 14,
    },
    stepContent: {
      flex: 1,
    },
    stepTitle: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 14,
      color: theme.colors.black,
      marginBottom: 6,
    },
    stepDesc: {
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 12,
      color: theme.colors.textSecondary,
      lineHeight: 18,
    },
    brandItem: {
      alignItems: 'center',
      gap: 8,
    },
    brandLabel: {
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 12,
      color: theme.colors.gray600,
    },
    mechanicBar: {
      marginHorizontal: 16,
      backgroundColor: theme.colors.white,
      borderRadius: 18,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      elevation: 4,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    mechanicLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    mechanicAvatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: theme.colors.faintGray,
    },
    mechanicName: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 14,
      color: theme.colors.black,
      marginBottom: 4,
    },
    mechanicMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 4,
    },
    mechanicJobs: {
      fontFamily: theme.fontfamily.poppinsRegular,
      fontSize: 12,
      color: theme.colors.gray500,
    },
    mechanicPrice: {
      backgroundColor: theme.colors.black,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      marginRight: 12,
    },
    mechanicPriceText: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 14,
    },
    mechanicArrow: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.darkGray,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mechanicArrowText: {
      color: theme.colors.white,
      fontSize: 18,
    },
    ratingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    starIcon: {
      color: theme.colors.GoldenYellow,
      fontSize: 14,
    },
    ratingText: {
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 14,
      color: theme.colors.textSecondary,
    },
  });
