import { StyleSheet } from 'react-native';
import { AppTheme } from '@theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    sectionCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 10,
      marginBottom: 8,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    bookingId: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.textSecondary,
      marginBottom: 8,
      textDecorationLine: 'underline',
    },
    serviceType: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.danger,
      marginBottom: 12,
    },
    serviceInfoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    serviceDetails: {
      flex: 1,
      paddingRight: 8,
    },
    serviceTitle: {
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.textPrimary,
      marginBottom: 8,
    },
    bulletRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    bulletText: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
      marginLeft: 4,
    },
    serviceImageWrapper: {
      position: 'relative',
    },
    serviceImage: {
      borderRadius: 8,
    },
    circle: {
      backgroundColor: theme.colors.white,
      padding: 2,
      borderRadius: 50,
    },
    addedBadge: {
      position: 'absolute',
      bottom: 8,
      right: 8,
      backgroundColor: theme.colors.greenBtn,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 5,
    },
    addedText: {
      fontSize: 10,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.white,
      marginLeft: 4,
    },
    sectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.black,
      marginLeft: 8,
    },
    issueInput: {
      paddingVertical: 12,
      paddingHorizontal: 4,
      minHeight: 80,
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textPrimary,
      textAlignVertical: 'top',
    },
    selectorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomColor: theme.colors.gray200,
      borderBottomWidth: 1,
    },
    selectorLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      backgroundColor: theme.colors.white,
      borderRadius: 50,
      padding: 2,
    },
    selectorText: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.DeepGreen,
      marginLeft: 8,
    },
    selectionBox: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    selectionInfo: {
      flex: 1,
      marginLeft: 12,
    },
    selectionTitle: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.textPrimary,
    },
    selectionSub: {
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textSecondary,
      marginTop: 4,
    },
    addAddressBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
      borderWidth: 1,
      borderColor: theme.colors.danger,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 6,
      alignSelf: 'flex-start',
    },
    addAddressText: {
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.danger,
      marginLeft: 4,
    },
    couponBadge: {
      backgroundColor: theme.colors.lightGreenSuccess,
      padding: 8,
      borderRadius: 8,
      marginTop: 8,
    },
    PercentageContainer: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      backgroundColor: theme.colors.DeepGreen,
      color: theme.colors.white,
      width: 24,
      height: 24,
      borderRadius: 12,
      textAlign: 'center',
      lineHeight: 24,
      overflow: 'hidden',
      marginRight: 8,
    },
    couponCode: {
      fontSize: 13,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.DeepGreen,
    },
    couponDesc: {
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.success,
      marginTop: 4,
    },
    savingBanner: {
      backgroundColor: theme.colors.red,
      flexDirection: 'row',
      alignItems: 'center',
      padding: 8,
      borderRadius: 8,
      marginBottom: 16,
    },
    savingText: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.white,
      marginLeft: 8,
    },
    paymentTypeSection: {
      marginTop: 8,
    },
    paymentTypeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    paymentOption: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.gray300,
      backgroundColor: theme.colors.background,
      borderRadius: 10,
      padding: 12,
      marginHorizontal: 4,
      alignItems: 'center',
    },
    paymentOptionSelected: {
      borderColor: theme.colors.DeepGreen,
      backgroundColor: theme.colors.lightGreenSuccess,
    },
    paymentOptionTitle: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.gray600,
      textAlign: 'center',
    },
    paymentOptionTitleSelected: {
      color: theme.colors.DeepGreen,
    },
    paymentOptionSub: {
      fontSize: 11,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.gray500,
      marginTop: 4,
      textAlign: 'center',
    },
    paymentOptionSubSelected: {
      color: theme.colors.DeepGreen,
    },
    payableCard: {
      backgroundColor: theme.colors.YellowLight,
      padding: 16,
      borderRadius: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 4,
    },
    payableLabel: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.darkOrange,
    },
    payableSub: {
      fontSize: 11,
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.orange,
      marginTop: 4,
    },
    payableValue: {
      fontSize: 18,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.DeepGreen,
    },
    modalContent: {
      padding: 20,
    },
    modalSubTitle: {
      fontSize: 14,
      color: theme.colors.gray500,
      marginBottom: 20,
    },
    paymentMethodItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.DeepGreen,
      backgroundColor: theme.colors.white,
      marginBottom: 30,
    },
    paymentMethodInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    razorpayIconPlaceholder: {
      width: 32,
      height: 32,
      borderRadius: 6,
      backgroundColor: theme.colors.razorpayBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    razorpayText: {
      color: theme.colors.white,
      fontSize: 18,
      fontWeight: 'bold',
    },
    paymentMethodName: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.black,
    },
    radioOuterActive: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: theme.colors.DeepGreen,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioInnerActive: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.colors.DeepGreen,
    },
    modalActionRow: {
      flexDirection: 'row',
      gap: 16,
    },
    modalCancelBtn: {
      flex: 1,
      paddingVertical: 16,
      alignItems: 'center',
      borderRadius: 10,
      backgroundColor: theme.colors.gray100,
    },
    modalCancelText: {
      color: theme.colors.gray600,
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
    },
    modalProceedBtn: {
      flex: 1,
      paddingVertical: 16,
      alignItems: 'center',
      borderRadius: 10,
      backgroundColor: theme.colors.DeepGreen,
    },
    modalProceedText: {
      color: theme.colors.white,
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
    },
    successModalOverlay: {
      flex: 1,
      backgroundColor: theme.colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    successModalContent: {
      backgroundColor: theme.colors.white,
      width: '80%',
      padding: 32,
      borderRadius: 20,
      alignItems: 'center',
    },
    successIconCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: theme.colors.success,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    successTitle: {
      fontSize: 18,
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.black,
      marginBottom: 4,
    },
    successSubTitle: {
      fontSize: 14,
      fontFamily: theme.fontfamily.poppinsMedium,
      color: theme.colors.success,
      textAlign: 'center',
    },
  });
