import { StyleSheet } from 'react-native';
import { SW, SH, SF } from '@utils/Dimensions';
import { AppTheme } from '@theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F8F9FA',
    },
    content: {
      paddingHorizontal: SW(16),
      paddingTop: SH(15),
      paddingBottom: SH(100),
    },
    sectionCard: {
      backgroundColor: theme.colors.white,
      borderRadius: SW(12),
      padding: SW(16),
      marginBottom: SH(16),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    bookingId: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoMedium,
      color: theme.colors.textSecondary,
      marginBottom: SH(10),
      textDecorationLine: 'underline',
    },
    serviceType: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.danger || '#D11C3D',
      marginBottom: SH(12),
    },
    serviceInfoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    serviceDetails: {
      flex: 1,
      paddingRight: SW(10),
    },
    serviceTitle: {
      fontSize: SF(16),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
      marginBottom: SH(8),
    },
    bulletRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: SH(4),
    },
    bulletText: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
      marginLeft: SW(6),
    },
    ratingPriceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: SH(10),
    },
    ratingText: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textSecondary,
      marginLeft: SW(4),
      marginRight: SW(12),
    },
    priceText: {
      fontSize: SF(15),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    strikePrice: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textMuted,
      textDecorationLine: 'line-through',
      marginLeft: SW(8),
    },
    serviceImageWrapper: {
      position: 'relative',
    },
    serviceImage: {
      borderRadius: SW(8),
    },
    circle: {
      backgroundColor: theme.colors.white,
      padding: SW(2),
      borderRadius: SW(50)
    },
    addedBadge: {
      position: 'absolute',
      bottom: SH(10),
      right: SW(30),
      backgroundColor: theme.colors.greenBtn,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: SW(8),
      paddingVertical: SH(4),
      borderRadius: SW(5),
    },
    addedText: {
      fontSize: SF(10),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.white,
      marginLeft: SW(4),
    },
    sectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: SH(12),
    },
    sectionTitle: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.black,
      marginLeft: SW(8),
    },
    issueInput: {
      backgroundColor: '#F9FAFB',
      borderWidth: 1,
      borderColor: theme.colors.border || '#E5E7EB',
      borderRadius: SW(8),
      padding: SW(12),
      minHeight: SH(80),
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textPrimary,
      textAlignVertical: 'top',
    },
    selectorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: SH(8),
      borderBottomColor: theme.colors.gray200,
      borderBottomWidth: 1
    },
    selectorLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      backgroundColor: theme.colors.white,
      borderRadius: SW(50),
      padding: SW(2)
    },
    selectorText: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.DeepGreen || '#105D38',
      marginLeft: SW(8),
    },
    selectionBox: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: SH(10),
    },
    selectionInfo: {
      flex: 1,
      marginLeft: SW(12),
    },
    selectionTitle: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    selectionSub: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
      marginTop: SH(4),
    },
    addAddressBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: SH(10),
      borderWidth: 1,
      borderColor: theme.colors.danger || '#D11C3D',
      paddingHorizontal: SW(12),
      paddingVertical: SH(6),
      borderRadius: SW(6),
      alignSelf: 'flex-start',
    },
    addAddressText: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoMedium,
      color: theme.colors.danger || '#D11C3D',
      marginLeft: SW(4),
    },
    couponBadge: {
      backgroundColor: '#ECFDF5',
      padding: SW(10),
      borderRadius: SW(8),
      marginTop: SH(10),
    },
    PercentageContainer: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      backgroundColor: theme.colors.DeepGreen,
      color: theme.colors.white,
      width: SW(24),
      height: SW(24),
      borderRadius: SW(12),
      textAlign: "center",
      lineHeight: SW(24),
      overflow: 'hidden',
      marginRight: SW(8),
    },
    couponCode: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.DeepGreen
    },
    couponDesc: {
      fontSize: SF(12),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.success || '#10B981',
      marginTop: SH(2),
    },
    savingBanner: {
      backgroundColor: theme.colors.red,
      flexDirection: 'row',
      alignItems: 'center',
      padding: SW(10),
      borderRadius: SW(8),
      marginBottom: SH(16),
    },
    savingText: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.white,
      marginLeft: SW(8),
    },
    billRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: SH(10),
    },
    billLabel: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
    },
    billValue: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoMedium,
      color: theme.colors.textPrimary,
    },
    discountLabel: {
      color: theme.colors.success || '#10B981',
      fontFamily: theme.fontfamily.robotoBold,
    },
    discountValue: {
      color: theme.colors.success || '#10B981',
    },
    taxNote: {
      fontSize: SF(11),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textMuted,
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.border || '#E5E7EB',
      marginVertical: SH(15),
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    totalLabel: {
      fontSize: SF(15),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    totalValue: {
      fontSize: SF(15),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
    },
    paymentTypeSection: {
      marginTop: SH(10),
    },
    paymentTypeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: SH(12),
    },
    paymentOption: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.border || '#E5E7EB',
      borderRadius: SW(10),
      padding: SW(12),
      marginHorizontal: SW(4),
      alignItems: 'center',
    },
    paymentOptionSelected: {
      borderColor: theme.colors.danger || '#D11C3D',
      backgroundColor: '#FEF2F2',
    },
    paymentOptionTitle: {
      fontSize: SF(13),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.textPrimary,
      textAlign: 'center',
    },
    paymentOptionSub: {
      fontSize: SF(11),
      fontFamily: theme.fontfamily.robotoRegular,
      color: theme.colors.textSecondary,
      marginTop: SH(4),
    },
    payableCard: {
      backgroundColor: '#FFF7ED',
      padding: SW(15),
      borderRadius: SW(10),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: SH(5),
    },
    payableLabel: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoBold,
      color: '#9A3412',
    },
    payableSub: {
      fontSize: SF(11),
      fontFamily: theme.fontfamily.robotoRegular,
      color: '#C2410C',
      marginTop: SH(2),
    },
    payableValue: {
      fontSize: SF(18),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.DeepGreen,
    },
    footer: {
      padding: SW(20),
      paddingBottom: SH(30),
      backgroundColor: theme.colors.white,
      borderTopWidth: 1,
      borderTopColor: theme.colors.gray100,
    },
    modalContent: {
      padding: SW(20),
    },
    modalSubTitle: {
      fontSize: SF(14),
      color: theme.colors.gray500,
      marginBottom: SH(20),
    },
    paymentMethodItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: SW(16),
      borderRadius: SW(12),
      borderWidth: 1,
      borderColor: theme.colors.DeepGreen,
      backgroundColor: theme.colors.white,
      marginBottom: SH(30),
    },
    paymentMethodInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SW(12),
    },
    razorpayIconPlaceholder: {
      width: SW(32),
      height: SW(32),
      borderRadius: SW(6),
      backgroundColor: '#3399FF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    razorpayText: {
      color: theme.colors.white,
      fontSize: SF(18),
      fontWeight: 'bold',
    },
    paymentMethodName: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoMedium,
      color: theme.colors.black,
    },
    radioOuterActive: {
      width: SW(20),
      height: SW(20),
      borderRadius: SW(10),
      borderWidth: 2,
      borderColor: theme.colors.DeepGreen,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioInnerActive: {
      width: SW(10),
      height: SW(10),
      borderRadius: SW(5),
      backgroundColor: theme.colors.DeepGreen,
    },
    modalActionRow: {
      flexDirection: 'row',
      gap: SW(15),
    },
    modalCancelBtn: {
      flex: 1,
      paddingVertical: SH(14),
      alignItems: 'center',
      borderRadius: SW(10),
      backgroundColor: theme.colors.gray100,
    },
    modalCancelText: {
      color: theme.colors.gray600,
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoMedium,
    },
    modalProceedBtn: {
      flex: 1,
      paddingVertical: SH(14),
      alignItems: 'center',
      borderRadius: SW(10),
      backgroundColor: theme.colors.DeepGreen,
    },
    modalProceedText: {
      color: theme.colors.white,
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoMedium,
    },
    successModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    successModalContent: {
      backgroundColor: theme.colors.white,
      width: '80%',
      padding: SW(30),
      borderRadius: SW(20),
      alignItems: 'center',
    },
    successIconCircle: {
      width: SW(80),
      height: SW(80),
      borderRadius: SW(40),
      backgroundColor: theme.colors.success || '#10B981',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: SH(20),
    },
    successTitle: {
      fontSize: SF(18),
      fontFamily: theme.fontfamily.robotoBold,
      color: theme.colors.black,
      marginBottom: SH(8),
    },
    successSubTitle: {
      fontSize: SF(14),
      fontFamily: theme.fontfamily.robotoMedium,
      color: theme.colors.success || '#10B981',
      textAlign: 'center',
    },
  });

