import { StyleSheet } from 'react-native';
import { AppTheme } from '@theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    content: {
      paddingBottom: 10,
    },
    profileBanner: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 100,
      backgroundColor: theme.colors.DeepGreen,
      borderBottomLeftRadius: 50,
      borderBottomRightRadius: 50,
    },
    avatarSection: {
      alignItems: 'center',
      marginTop: 20,
      marginBottom: 20,
      zIndex: 1,
    },
    avatarWrapper: {
      position: 'relative',
      padding: 4,
      backgroundColor: theme.colors.white,
      borderRadius: 55,
      elevation: 10,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 15,
    },
    avatarImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: theme.colors.gray50,
    },
    editBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.DeepGreen,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: theme.colors.white,
      elevation: 4,
    },
    formCard: {
      backgroundColor: theme.colors.white,
      borderRadius: 20,
      paddingHorizontal: 16,
      elevation: 3,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      borderWidth: 1.5,
      borderColor: theme.colors.white,
      marginBottom: 20,
      marginHorizontal: 16,
      zIndex: 2,
      paddingVertical: 20
    },
    inputField: {
      paddingVertical: 18,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.gray50,
    },
    inputLabel: {
      color: theme.colors.gray500,
      fontSize: 12,
      fontFamily: theme.fontfamily.poppinsMedium,
      marginBottom: 6,
    },
    input: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontFamily: theme.fontfamily.poppinsRegular,
      padding: 0,
      height: 24,
    },
    footer: {
      padding: 20,
      backgroundColor: 'transparent',
      gap: 15,
      paddingBottom: 30,
    },
    saveButton: {
      backgroundColor: theme.colors.DeepGreen,
      borderRadius: 12,
      height: 54,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 3,
      shadowColor: theme.colors.DeepGreen,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    saveButtonText: {
      color: theme.colors.white,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 16,
      letterSpacing: 0.5,
    },
    deleteButton: {
      height: 54,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.brandRedLight,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.colors.error,
    },
    deleteButtonText: {
      color: theme.colors.error,
      fontFamily: theme.fontfamily.poppinsMedium,
      fontSize: 14,
    },
    modalContent: {
      padding: 20,
      alignItems: 'center',
    },
    modalIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: theme.colors.brandRedLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      marginBottom: 8,
      textAlign: 'center',
    },
    modalDesc: {
      marginBottom: 24,
      textAlign: 'center',
      lineHeight: 20,
    },
    modalActions: {
      width: '100%',
      gap: 12,
    },
    confirmDeleteBtn: {
      backgroundColor: theme.colors.error,
      height: 48,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cancelBtn: {
      backgroundColor: theme.colors.gray50,
      height: 48,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
