import { StyleSheet } from 'react-native';
import { AppTheme } from '@theme';
import { SW, SH } from '@utils/Dimensions';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    profileHeader: {
      paddingHorizontal: SW(16),
      paddingTop: SH(10),
      paddingBottom: SH(8),
    },
    profileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.white,
      paddingHorizontal: SW(16),
      paddingVertical: SH(10),
      borderRadius: SW(20),
      elevation: 4,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
      overflow: 'hidden',
    },
    imageContainer: {
      marginRight: SW(12),
    },
    avatarPlaceholder: {
      width: SW(54),
      height: SW(54),
      borderRadius: SW(27),
      backgroundColor: theme.colors.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
    },
    userInfo: {
      flex: 1,
    },
    userName: {
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.textPrimary,
    },
    userEmail: {
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textMuted,
      marginTop: SH(2),
    },
    myTractorButton: {
      paddingHorizontal: SW(16),
      marginBottom: SH(10),
    },
    myTractorContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.white,
      padding: SW(10),
      borderRadius: SW(16),
      elevation: 3,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
      borderLeftWidth: 3,
      borderLeftColor: theme.colors.brandRed,
    },
    myTractorLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    tractorIconContainer: {
      width: SW(36),
      height: SW(36),
      borderRadius: SW(10),
      backgroundColor: theme.colors.brandRed + '10',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: SW(12),
    },
    sectionContainer: {
      marginHorizontal: SW(16),
      backgroundColor: theme.colors.white,
      borderRadius: SW(16),
      marginBottom: SH(10),
      paddingVertical: SH(8),
      elevation: 3,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
      borderLeftWidth: 3,
      borderLeftColor: theme.colors.brandRed,
    },
    sectionTitle: {
      paddingHorizontal: SW(16),
      paddingTop: SH(8),
      paddingBottom: SH(12),
      color: theme.colors.textPrimary,
      fontFamily: theme.fontfamily.poppinsSemiBold,
    },
    socialSection: {
      paddingHorizontal: SW(16),
      paddingTop: SH(10),
      paddingBottom: SH(30),
      alignItems: 'center',
    },
    socialTitle: {
      marginBottom: SH(16),
      fontFamily: theme.fontfamily.poppinsMedium,
    },
    socialIconsRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: SW(20),
    },
    socialItem: {
      alignItems: 'center',
      gap: SH(6),
    },
    socialIconWrapper: {
      width: SW(48),
      height: SW(48),
      borderRadius: SW(24),
      backgroundColor: theme.colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 2,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
    },
  });
