import { StyleSheet } from 'react-native';
import { AppTheme } from '@theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    profileHeader: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 8,
    },
    profileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.white,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 20,
      elevation: 4,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
      overflow: 'hidden',
    },
    imageContainer: {
      marginRight: 12,
    },
    avatarPlaceholder: {
      width: 54,
      height: 54,
      borderRadius: 27,
      backgroundColor: theme.colors.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
    },
    userInfo: {
      flex: 1,
    },
    userName: {
      fontFamily: theme.fontfamily.poppinsSemiBold,
      color: theme.colors.textPrimary,
    },
    userEmail: {
      fontFamily: theme.fontfamily.poppinsRegular,
      color: theme.colors.textMuted,
      marginTop: 2,
    },
    myTractorButton: {
      paddingHorizontal: 16,
      marginBottom: 10,
    },
    myTractorContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.white,
      padding: 10,
      borderRadius: 16,
      elevation: 3,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
      borderLeftWidth: 3,
      borderLeftColor: theme.colors.brandRed,
    },
    myTractorLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    tractorIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.colors.brandRed + '10',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    sectionContainer: {
      marginHorizontal: 16,
      backgroundColor: theme.colors.white,
      borderRadius: 16,
      marginBottom: 10,
      paddingVertical: 8,
      elevation: 3,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
      borderLeftWidth: 3,
      borderLeftColor: theme.colors.brandRed,
    },
    sectionTitle: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
      color: theme.colors.textPrimary,
      fontFamily: theme.fontfamily.poppinsSemiBold,
    },
    socialSection: {

      marginHorizontal: 16,
      backgroundColor: theme.colors.white,
      borderRadius: 16,
      marginBottom: 10,
      paddingVertical: 8,
      elevation: 3,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
      borderLeftWidth: 3,
      borderLeftColor: theme.colors.brandRed,
      // alignItems: 'center',
    },
    socialTitle: {
      marginBottom: 16,
      fontFamily: theme.fontfamily.poppinsMedium,
      paddingHorizontal: 15
    },
    socialIconsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 20,
      marginHorizontal: 20
    },
    socialItem: {
      alignItems: 'center',
      gap: 6,
    },
    socialIconWrapper: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 2,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      borderWidth: 1,
      borderColor: theme.colors.borderFaint,
    },
  });
